name: xmpp_stone

description: "Xmpp Stone is lightweight XMPP client library written completely in Dart."

version: 0.3.3

homepage: https://vukoye.github.io

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  xml: ^6.1.0
  cryptoutils: ^0.5.0
  crypto: ^3.0.2
  synchronized: ^3.0.0+3
  tuple: ^2.0.0
  unorm_dart: ^0.2.0
  image: ^3.2.0
  quiver: ^3.1.0 #hash code generator
  console: ^4.1.0 #for example
  intl: ^0.17.0
  collection: ^1.16.0
  universal_io: ^2.0.4
  web_socket_channel: ^2.2.0

dev_dependencies:
  test: ^1.21.4
  mockito: ^5.3.1
