name: xmpp_stone

description: "Xmpp Stone is lightweight XMPP client library written completely in Dart."

version: 0.3.3

homepage: https://vukoye.github.io

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  xml: ^5.1.0
  cryptoutils: ^0.5.0
  crypto: ^3.0.1
  synchronized: ^3.0.0
  tuple: ^2.0.0
  unorm_dart: ^0.2.0
  image: ^3.0.2
  quiver: ^3.0.1 #hash code generator
  console: ^4.0.0 #for example
  intl: ^0.17.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.3
