name: xmpp_stone

description: "Xmpp Stone is lightweight XMPP client library written completely in Dart."

version: 0.3.3

homepage: https://vukoye.github.io

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  xml: ^4.0.0
  cryptoutils: ^0.4.0
  crypto: ^2.0.6
  synchronized: ^2.1.0
  tuple: ^1.0.2
  unorm_dart: ^0.1.1
  image: ^2.0.7
  quiver: '>=2.0.0 <3.0.0' #hash code generator
  console: ^3.1.0 #for example
  intl: ^0.16.1

dev_dependencies:
  test: ^1.0.0
  mockito: ^4.0.0
