name: xmpp_stone

description: "Xmpp Stone is lightweight XMPP client library written completely in Dart."

version: 0.3.3

homepage: https://vukoye.github.io

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  xml: ^5.3.0
  cryptoutils: ^0.5.0
  crypto: ^3.0.0
  synchronized: ^3.0.0
  tuple: ^2.0.0
  unorm_dart: ^0.2.0
  image: ^3.0.7
  quiver: '3.0.1+1' #hash code generator
  console: ^4.1.0
  intl: ^0.17.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.0.0
  mockito: ^5.0.17
